name: Sulfuris
version: '${project.version}'
main: fr.sulfuris.dev.main
api-version: 1.16
description: SulfurisPL
author: SulfurisDev
url: www.sulfuris.fr
commands:
  store:
    description: Store a message in a item
    usage: /store <message>
    aliases:
      - store
      - storemsg
      - storemessage
      - storemsg
      - storemessage
    permission: sulfuris.store
    permission-message: You don't have permission to use this command.
  money:
    description: Give money to a player
    usage: /givemoney <player> <amount>
    aliases:
      - givemoney
    permission: sulfuris.money
    permission-message: You don't have permission to use this command.
  serverinfo:
    description: Display server information
    usage: /serverinfo
    aliases:
      - serverinfo
      - server
    permission: sulfuris.serverinfo
    permission-message: You don't have permission to use this command.
