name: Sulfuris
version: '${project.version}'
main: fr.sulfuris.dev.Main
api-version: 1.16
description: Sulfuris plugin made for minecraft roleplay
author: D3adPlaysVR, Meliodouil
url: www.sulfuris.fr
softdepend: [ WorldGuard ]
commands:
  svehicles:
    usage: /svehicles
    description: main command for sulfuris vehicles
  store:
    description: Store a message in a item
    usage: /store <message>
    aliases:
      - store
      - storemsg
      - storemessage
      - storemsg
      - storemessage
    permission: sulfuris.store
    permission-message: You don't have permission to use this command.
  money:
    description: Give money to a player
    usage: /givemoney <player> <amount>
    aliases:
      - givemoney
    permission: sulfuris.money
    permission-message: You don't have permission to use this command.
  serverinfo:
    description: Display server information
    usage: /serverinfo
    aliases:
      - serverinfo
      - server
    permission: sulfuris.serverinfo
    permission-message: You don't have permission to use this command.
  givepack:
    description: Give a pack to a player
    usage: /givepack <player> <pack>
    aliases:
      - givepack
    permission: sulfuris.givepack
    permission-message: You don't have permission to use this command.
  givekey:
    description: Give a key to a player
    usage: /givekey <player> <key>
    aliases:
      - givekey
    permission: sulfuris.givekey
    permission-message: You don't have permission to use this command.
  givebooster:
    description: Give a booster to a player
    usage: /givebooster <player> <booster>
    aliases:
      - givebooster
    permission: sulfuris.givebooster
    permission-message: You don't have permission to use this command.
  givelevel:
    description: Give a level to a player
    usage: /givelevel <player> <level>
    aliases:
      - givelevel
    permission: sulfuris.givelevel
    permission-message: You don't have permission to use this command.
  givemoney:
    description: Give money to a player
    usage: /givemoney <player> <ammount>
    aliases:
      - givemoney
    permission: sulfuris.givemoney
    permission-message: You don't have permission to use this command.
  setmoney:
    description: Set money to a player
    usage: /setmoney <player> <ammount>
    aliases:
      - setmoney
    permission: sulfuris.setmoney
    permission-message: You don't have permission to use this command.
  adminbank:
    description: Admin bank
    usage: /adminbank <player>
    aliases:
      - adminbank
    permission: sulfuris.adminbank
    permission-message: You don't have permission to use this command.
  moneygive:
    description: Give money to a player
    usage: /moneygive <player> <ammount>
    aliases:
      - moneygive
    permission: sulfuris.moneygive
    permission-message: You don't have permission to use this command.
  moneyset:
    description: Set money to a player
    usage: /moneyset <player> <ammount>
    aliases:
      - moneyset
    permission: sulfuris.moneyset
    permission-message: You don't have permission to use this command.
  moneyreset:
    description: Reset money to a player
    usage: /moneyreset <player>
    aliases:
      - moneyreset
    permission: sulfuris.moneyreset
    permission-message: You don't have permission to use this command.
  setjob:
    description: Set job to a player
    usage: /setjob <player> <job>
    aliases:
      - setjob
    permission: sulfuris.setjob
    permission-message: You don't have permission to use this command.
  removedata:
    description: Remove data from a player
    usage: /removedata <player>
    aliases:
      - removedata
    permission: sulfuris.removedata
    permission-message: You don't have permission to use this command.
  sit:
    description: Sit down
    usage: /sit
    aliases:
      - sit
    permission: sulfuris.sit
    permission-message: You don't have permission to use this command.


