name: Sulfuris
version: '${project.version}'
main: fr.sulfuris.dev.main
api-version: 1.16
description: SulfurisPL
author: SulfurisDev
url: www.sulfuris.fr
commands:
  store:
    description: Store a message in a item
    usage: /store <message>
    aliases:
      - store
      - storemsg
      - storemessage
      - storemsg
      - storemessage
    permission: sulfuris.store
    permission-message: You don't have permission to use this command.
  money:
    description: Give money to a player
    usage: /givemoney <player> <amount>
    aliases:
      - givemoney
    permission: sulfuris.money
    permission-message: You don't have permission to use this command.
  serverinfo:
    description: Display server information
    usage: /serverinfo
    aliases:
      - serverinfo
      - server
    permission: sulfuris.serverinfo
    permission-message: You don't have permission to use this command.
  givepack:
    description: Give a pack to a player
    usage: /givepack <player> <pack>
    aliases:
      - givepack
    permission: sulfuris.givepack
    permission-message: You don't have permission to use this command.
  givekey:
    description: Give a key to a player
    usage: /givekey <player> <key>
    aliases:
      - givekey
    permission: sulfuris.givekey
    permission-message: You don't have permission to use this command.
  givebooster:
    description: Give a booster to a player
    usage: /givebooster <player> <booster>
    aliases:
      - givebooster
    permission: sulfuris.givebooster
    permission-message: You don't have permission to use this command.
  givelevel:
    description: Give a level to a player
    usage: /givelevel <player> <level>
    aliases:
      - givelevel
    permission: sulfuris.givelevel
    permission-message: You don't have permission to use this command.
